### ISSUE TITLE
Node is throwing a MaxListenersExceededWarning

### ISSUE THREAD

**Issue by ROSeaboyer** [serverless/compose#114]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When running a deployment with the below configuration, I get a MaxListenersExceededWarning when serviceD and serviceE start their deployment. This occurs regardless of which service of serviceB, serviceC, and serviceF finish deploying last.

Not the biggest deal, just something I thought I'd bring up.

node: 16.14.2
@serverless/compose: 1.0.2

### Service configuration (serverless-compose.yml) content

```yaml
services:
  serviceA:
    path: serviceA
  serviceB:
    path: serviceB
    dependsOn:
      - serviceA
  serviceC:
    path: serviceC
    dependsOn:
      - serviceA
  serviceD:
    path: serviceD
    dependsOn:
      - serviceA
      - serviceB
  serviceE:
    path: serviceE
    dependsOn:
      - serviceA
      - serviceC
  serviceF:
    path: serviceF
    dependsOn:
      - serviceA
```

### Command name and used flags

serverless deploy --stage ryan

### Command output

```shell
(node:41560) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```
