### ISSUE TITLE
Serverless compose throws an error Impossible to parse the output of "serverless info":

### ISSUE THREAD

**Issue by fuzzy28** [serverless/compose#145]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I run sls deploy --stage stg to my serverless-compose.ts, it throws an error Impossible to parse the output of "serverless info": and skip the next service.

### Service configuration (serverless-compose.yml) content

```yaml
const serverlessCompose = {
    services: {
        infra: {
            path: "../app-infra"
        },

        service1: {
            path: "../app-service1",
            dependsOn: ["infra"]
        }
    }
}

module.exports = serverlessCompose;
```

### Command name and used flags

sls deploy --stage stg

### Command output

```shell
Impossible to parse the output of "serverless info":
Service Information
service: app-infra
stage: stg
region: ap-southeast-1
stack: app-infra-stg
resources: 22
api keys:
  None
endpoints:
functions:
  None
layers:
  None

Stack Outputs
APIGatewayRestApiRootResourceId: xxxx
ApiGatewayRestApiId: xxxx
CognitoUserPoolApplicationUserPoolId: xxxx
CognitoUserPoolApplicationUserPoolClientId: xxxx
APIGatewayCognitoAuthorizer: xxxx
CognitoUserPoolARN: xxxx
ServerlessDeploymentBucketName: xxxx


infra >     at ServerlessFramework.retrieveOutputs (xxxxx-path-serverless-compose\node_modules\@serverless\compose\components\framework\index.js:307:11)
infra >     at processTicksAndRejections (node:internal/process/task_queues:96:5)
infra >     at async ServerlessFramework.deploy (xxxxx-path-serverless-compose\node_modules\@serverless\compose\components\framework\index.js:92:40)
infra >     at async fn (xxxxx-path-serverless-compose\node_modules\@serverless\compose\src\ComponentsService.js:519:11)
service1> skipped



```
