### ISSUE TITLE
Monorepo with serverless-python-requirements breaks plugin packaging

### ISSUE THREAD

**Issue by david-a-jetter** [serverless/compose#152]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm not sure if this is better filed here or in https://github.com/serverless/serverless-python-requirements

Use case: A Python monorepo with all pypi requirements managed through Poetry in a single `pyproject.toml` file, containing multiple Serverless services, each using `serverless-python-requirements` [plugin ](https://github.com/serverless/serverless-python-requirements) being migrated from serialized `serverless deploy` commands to Serverless Compose.

After moving each service's yml file into its own subdirectory, adding the requisite `serverless-compose.yml` in the root, and running `npx sls deploy`, each package's zip file contains just the source code and no python packages. The `serverless-python-requirements` plugin did not run at all. The repository structure is roughly outlined as:

```
pyproject.toml
poetry.lock
serverless-compose.yml
src/
package/
  - appone/
    - serverless.appone.yml
  - apptwo/
    - serverless.apptwo.yml
  - appthree/
    - serverless.appthree.yml
```

Workaround: Use copyfiles npm package (which ensures cross-platform compatibility) to copy the `pyproject.toml` file into each app's subdirectory, eg: `npx copyfiles pyproject.toml package/appone` before running `npx sls deploy` and the `serverless-python-requirements` plugin behaves as expected.

### Service configuration (serverless-compose.yml) content

```yaml
services:
  appone:
    path: package/appone
    config: serverless.appone.yml
  apptwo:
    path: package/apptwo
    config: serverless.apptwo.yml
  appthree:
    path: package/appthree
    config: serverless.appthree.yml
```

### Command name and used flags

npx serverless deploy --stage dev

### Command output

```shell
N/A
```
