### ISSUE TITLE
Recognise Ouputs

### ISSUE THREAD

**Issue by jcampbell05** [serverless/compose#161]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Currently the only outputs supported are those exposed by CloudResources but some outputs can only be expressed or rather are easier to express by using Serverless outputs.

However compose doesn't support these.

What I would love to be able to express is the following:

```
services:
  api:
    path: main-serverless-api
  ai:
    path: serverless-ai
   dep:
      enhancementResultQueue: ${output:api.enhancementResultQueue}
```

But it currently just isn't possible instead I have to do it by making ai explicitly depend on ai and reference the option from within the ai yml file.
