### ISSUE TITLE
Cannot run hook scripts in monorepo

### ISSUE THREAD

**Issue by 596050** [serverless/compose#165]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hello,

I''m trying to run hook scripts in individual apps for a monorepo.

When I try using the scripts plugins hooks:
```
serverless-plugin-scripts
```
and
```
serverless-scriptable-plugin
```
with something like
```js
  custom: {
   ...
     scriptable: {
        // hooks used to invoke a lambda at the end of the deploy to populate the app secrets
        hooks: {
          "after:package:finalize": "sls invoke -f populateSSM",
        },
     }
  }
```
<img width="128" alt="Screenshot 2022-11-23 at 13 10 26" src="https://user-images.githubusercontent.com/19141517/203554955-fda6fc97-a57b-4f32-92f7-26d09b5a785b.png">

Deployment is stuck, when I remove the hook script, it deploys as expected.

Do you know why that would be and where a fix needs to be made?

### Service configuration (serverless-compose.yml) content

```yaml
services:
  infrastructure-identity-verification:
    path: ./apps/infrastructure-identity-verification

  auth-service:
    path: ./apps/auth-service
    dependsOn:
      - infrastructure-identity-verification

  workers:
    path: ./apps/workers
    dependsOn:
      - infrastructure-identity-verification

  public-identity-verification:
    path: ./apps/public-identity-verification
    dependsOn:
      - infrastructure-identity-verification
      - workers
```

### Command name and used flags

serverless deploy --stage=staging

### Command output

```shell
N/A - output just hangs
```
