### ISSUE TITLE
Variable Reference fails for files in service root (not at project root)

### ISSUE THREAD

**Issue by amsand11** [serverless/compose#181]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have the following setup
``` 
# serverless-compose.yml
services:
  my-cool-service:
    path: my-cool-service
  another-service:
    path: another-service
   
   
# /my-cool-service/serverless.yml
provider:
  environment: 
    ENV_FOO: ${file(my-cool-service/serverless.localdev.yml):CONFIG_FOO}
    # ENV_FOO: ${file(/my-cool-service/serverless.localdev.yml):CONFIG_FOO}    # same error
    # ENV_FOO: ${file(./my-cool-service/serverless.localdev.yml):CONFIG_FOO}   # same error
    

# /my-cool-service/serverless.localdev.yml
CONFIG_FOO: foo
``` 

And this yields the following error:
```
"Cannot resolve serverless.yml: Variables resolution errored with: 
 - Cannot resolve variable at "provider.environment.ENV_FOO": Value not found at "file" source.
```

I would generally expect to have service specific config files, but thus far the only resolution I've been able to get working are files that live at the project root.  This is a fine workaround for my limited/simple use case right now, but I often prefer to keep configuration items isolated to the specific "thing" (i.e. service) that needs them.

### Service configuration (serverless-compose.yml) content

```yaml
# serverless-compose.yml
services:
  my-cool-service:
    path: my-cool-service
  another-service:
    path: another-service
   
   
# /my-cool-service/serverless.yml
provider:
  environment: 
    ENV_FOO: ${file(my-cool-service/serverless.localdev.yml):CONFIG_FOO}
    # ENV_FOO: ${file(/my-cool-service/serverless.localdev.yml):CONFIG_FOO}    # same error
    # ENV_FOO: ${file(./my-cool-service/serverless.localdev.yml):CONFIG_FOO}   # same error
    

# /my-cool-service/serverless.localdev.yml
CONFIG_FOO: foo
```

### Command name and used flags

serverless my-cool-service:print --stage localdev

### Command output

```shell
Cannot resolve serverless.yml: Variables resolution errored with: 
 - Cannot resolve variable at "provider.environment.ENV_FOO": Value not found at "file" source.
```
