### ISSUE TITLE
NPM packages of serverless plugins are installed in the compose root-folder instead of the services folders

### ISSUE THREAD

**Issue by jimmyorpheus** [serverless/compose#191]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When executing the following command 
```sh
sls plugin install --name=serverless-somePlugin --service=someService
```
from the serverless-compose root-folder (the folder with the serverless-compose.yml file), the plugin is correctly added to the configuration at ./someService/serverless.yml):

```yml
plugins:
  - serverless-somePlugin
```
But the npm package of the plugin is installed directly at the compose level
```
./package.json
./package-lock.json
./node_modules/serverless-somePlugin
```

 instead of being installed to the subfolder of the specific service which the plugin is meant for.
```

./someService/package.json
./someService/package-lock.json
./someService/node_modules/serverless-somePlugin
``` 

### Service configuration (serverless-compose.yml) content

```yaml
# BEFORE COMMAND EXECUTION
service: someService
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: dev
  profile: someProfile

functions:
  someFunction:
    handler: index.handler

# AFTER COMMAND EXECUTION
service: someService
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: dev
  profile: someProfile

functions:
  someFunction:
    handler: index.handler

plugins:
  - serverless-somePlugin
```

### Command name and used flags

sls plugin install --name=serverless-somePlugin --service=someService

### Command output

```shell
Installing plugin "serverless-somePlugin"

✔ Plugin "serverless-somePlugin" installed  (14s)
```
