### ISSUE TITLE
[RFC] Simplify services definition by optionally omitting "path" parameter

### ISSUE THREAD

**Issue by m-radzikowski** [serverless/compose#36]
**Proposal**

The service name will be the same as the path name in 99% cases (based solely on my experience 😛 ). I suggest simplifying the services definition by omitting the path if it's the same as the service name.

Additionally, since I put all services in a separate directory, additional config parameter could be used to define base path to services.

Example:

```yaml
name: myapp

servicesPath: ./myservices/ # optional, defaults to .

services:
  serv1: # located in ./myservices/serv1, no additional config is needed, just the name
  serv2:
    params:
      tableName: ${serv1.tableName}
```
