### ISSUE TITLE
[RFC] Common parameters

### ISSUE THREAD

**Issue by m-radzikowski** [serverless/compose#38]
**Problem**

In monorepo services often use the same parameters. Right now the solution to share parameters is to create a separate file and read params with `${file()}` in each stack.

I have two types of such common parameters in my projects:

- depending on the stage, for example:
  - log level (info on prod, debug elsewhere)
  - lambda insights (enable on prod only)
- values that do not change but I want to parameterize them instead of repeating, for example:
  - project name (to keep CF stacks name consistent and related to each other)

**Proposal**

Introduce common/global parameters in serverless-compose. Those parameters will be passed to all services.

Use the `params` feature syntax introduces in Serverless Framework v3.

Example:

```yaml
name: myapp

params:
  prod:
    logLevel: info
    lambdaInsights: true
  default:
    logLevel: debug
    lambdaInsights: false
    projectName: myapp # bonus points if you can do ${self:name} here :D

services:
  serv1: # will get logLevel, lambdaInsights, and projectName parameters
    path: services/serv1
  serv2: # will get logLevel, lambdaInsights, projectName, and tableName parameters
    path: services/serv2
    params:
      tableName: ${serv1.tableName}
```

**Comment by mnapoli** [comment]
Interesting, thanks for opening this.

One first (obvious) step to this would be to support stage parameters (`params` in `serverless-compose.yml`), and I think this one will make sense to support eventually.

However the second step, auto-injecting Compose parameters in services, might be a bit more tricky. Indeed, it makes 100% sense to do that right now, but in the future we want to consider supporting other kinds of "services" (aka components). For example to deploy CDK constructs, or services of other cloud providers, etc. in these other kinds of "components", the `params` option might not exist at all.

Here's an example:

```yml
name: myapp

params:
  prod:
    logLevel: info
  default:
    logLevel: debug

services:

  api:
    component: serverless-framework
    path: api
    params:
      logLevel: ${param:logLevel}

  website:
    component: website
    build: 'npm run build'
    domain: example.com
```

In the example above, the `website` component doesn't have `params` (the component options are directly set on the component properties).

Maybe another approach to solve the root problem might be to think about "default values" that apply to all components of a certain type. (and again, to be clear, I'm talking about a future where multiple kinds of components exist)

For example:

```yml
name: myapp

params:
  prod:
    logLevel: info
  default:
    logLevel: debug

# Default settings
defaults:
  serverless-framework:
    params:
      logLevel: ${param:logLevel}

services:

  api:
    component: serverless-framework
    path: api
    params:
      logLevel: ${param:logLevel}

  website:
    component: website
    build: 'npm run build'
    domain: example.com
```

Granted, this isn't as automated as the solution initially proposed. But that could be a more generic solution for the long term?

Finally, another approach could be to have special behavior for Serverless Framework services where we inject all params (and that behavior is not implemented for other components). That's also something we could consider after all…
