### ISSUE TITLE
`${foo:bar}` syntax is confused with `${foo.bar}` syntax

### ISSUE THREAD

**Issue by mnapoli** [serverless/compose#64]
```yaml
services:
  subscriptions:
    path: subscriptions
    params:
      foo: ${param:bar}
```

The config above throws the following error:

> The service "param:bar" does not exist. It is referenced by "subscriptions" in expression "${param:bar}".

From my debug it seems like [this regex](https://github.com/serverless/compose/blob/68b996cd30e6654d958070bbb72980af4e5099b5/src/ComponentsService.js#L148) matches `${param:bar}`, and then [this line](https://github.com/serverless/compose/blob/68b996cd30e6654d958070bbb72980af4e5099b5/src/ComponentsService.js#L155) does not detect that there was no `.` in the string. So it considers "param:bar" as the service name.

Instead we should get an error that says that `param` isn't a valid variable source (or something of the sort?).
