### ISSUE TITLE
Make `path` required and forbid `.`

### ISSUE THREAD

**Issue by mnapoli** [serverless/compose#88]
We want to avoid infinite recursion in those scenarios:

```yaml
services:
  foo:
    path: .
```

So:

- `.` shouldn't be allowed for `path`
- `path` should be required
