### ISSUE TITLE
Params not being resolved properly

### ISSUE THREAD

**Issue by r-token** [serverless/compose#96]
I’m having issues with params I set within the `serverless-compose.yml` file.

**Scenario**: I output ARNs from various services and reference them in other services within the IAM role statements block.

However, when deploying my services with Compose, I get an error that says `Resource ${services/my-service.MyOutput} must be in ARN format or "*".`

This was working fine when I used CloudFormation imports via `Fn::ImportValue` from each service. But when trying to use Compose’s params, it looks like the param is not being resolved to the actual ARN. It’s just showing as the literal param value of `${services/my-service.MyOutput}`

My guess is that this is happening because all of my services live within a `services` directory, not at the root (where the compose file is). If that's all it is, I can move my `serverless-compose.yml` file to inside the `services` directory for now. Does the `serverless-compose.yml` file **need** to live at the same level as the services themselves?

Example:

```
# serverless-compose.yml (at project root)

services:
  my-service:
    path: services/my-service

  my-second-service:
    path: services/my-second-service
    params:
      tableOne: ${services/my-service.TableOneArn}
      tableTwo: ${services/my-service.TableTwoArn}
    dependsOn:
      my-service
```

```
# serverless.yml for my-second-service (at services/my-second-service)

provider:
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource:
            - ${param:tableOne}
            - ${param:tableTwo}
```

Deploying this with Compose will return an error that says `Resource ${services/my-service.TableOneArn} must be in ARN format or "*"`
